#! /bin/sh

#set -e -x

mkdir -p $SNAP_COMMON/ppd
mkdir -p $SNAP_COMMON/spool
mkdir -p $SNAP_COMMON/cups/ssl
mkdir -p $SNAP_COMMON/tmp
chmod 1777 $SNAP_COMMON/tmp >/dev/null 2>&1 || :

export TMPDIR=$SNAP_COMMON/tmp
export FILTER_DIR=$SNAP/usr/lib/hplip-printer-app/filter
export BACKEND_DIR=$SNAP/usr/lib/hplip-printer-app/backend
export TESTPAGE_DIR=$SNAP/usr/share/hplip-printer-app
export PPD_PATHS=$SNAP/usr/share/ppd/:$SNAP_COMMON/ppd/
export STATE_FILE=$SNAP_COMMON/hplip-printer-app.state
export SPOOL_DIR=$SNAP_COMMON/spool
export CUPS_SERVERROOT=$SNAP_COMMON/cups

exec $SNAP/usr/bin/hplip-printer-app $*
