name: hplip-printer-app
base: core20
version: '1.0'
summary: HPLIP Printer Application
description: |
  The HPLIP Printer Application is a PAPPL (Printer Application
  Framework) based Printer Application to support printers using the
  printer driver of HPLIP. PostScript printing is not supported (use
  the PostScript Printer Application). Support for scanning and for
  the proprietary plugin will be added later.

grade: stable
confinement: strict

# Only build on the architectures supported
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

# Make resolution of ".local" host names (Zero-Conf/mDNS/DNS-SD)
# working: Mirror nsswitch.conf with added mDNS look-up support into
# /etc/nsswitch.conf
# See: https://forum.snapcraft.io/t/how-can-i-lookup-host-name-from-snap-core-using-avahi-mdns/
layout:
  /etc/nsswitch.conf:
    bind-file: $SNAP/etc/nsswitch.conf

environment:
  MIBDIRS: /snap/hplip-printer-app/current/usr/share/snmp/mibs:/snap/hplip-printer-app/current/usr/share/snmp/mibs/iana:/snap/hplip-printer-app/current/usr/share/snmp/mibs/ietf

apps:
  hplip-printer-app-server:
    command: scripts/run-hplip-printer-app-server
    daemon: simple
    plugs: [avahi-control, home, network, network-bind, raw-usb]
  hplip-printer-app:
    command: scripts/run-hplip-printer-app
    plugs: [avahi-control, home, network, network-bind, raw-usb]

parts:
  patches:
    plugin: dump
    source: snap/local/
    organize:
      '*.patch' : patches/
    override-prime: ""

  jpeglib:
    plugin: autotools
    source: https://www.ijg.org/files/jpegsrc.v9d.tar.gz
    source-type: tar
    autotools-configure-parameters:
      - --prefix=/usr
    prime:
      - -etc/fonts
      - -var
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -snap
      - usr/lib/libjpeg.so.9
      - usr/lib/libjpeg.so.9.4.0

  pappl:
    source: https://github.com/michaelrsweet/pappl
    source-type: git
    plugin: autotools
    override-build: |
      set -eux
      patch -p1 < $SNAPCRAFT_STAGE/patches/pappl-support-text-string-vendor-options.patch
      snapcraftctl build
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-papplstatedir=/var/snap/hplip-printer-app/common
      - --with-papplsockdir=/var/snap/hplip-printer-app/common/tmp
      - --enable-libjpeg
      - --enable-libpng
      - --enable-libusb
      - --with-dnssd=avahi
    build-packages:
      - libavahi-client-dev
      - libgnutls28-dev
      - libjpeg-dev
      - libpam0g-dev
      - libpng-dev
      - libusb-1.0-0-dev
      - zlib1g-dev
    stage-packages:
      - libavahi-client3
      - libpng16-16
      - libusb-1.0-0
    prime:
      - -etc/fonts
      - lib
      - -var
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -snap
      - usr/lib/libpappl.so.1
    after: [patches, jpeglib]

  pappl-retrofit:
    source: https://github.com/openprinting/pappl-retrofit
    source-type: git
    plugin: autotools
    override-build: |
      set -eux
      patch -p1 < $SNAPCRAFT_STAGE/patches/support-new-pappl-string-options.patch
      snapcraftctl build
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - autoconf
      - automake
      - libtool
      - autotools-dev
      - pkg-config
      - perl-base
    prime:
      - -var
      - -usr/bin/test-printer-app
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/lib/test-printer-app
      - -usr/share/
      - -snap
    after: [patches, cups, cups-filters, pappl]

  qpdf:
    source: https://github.com/qpdf/qpdf/releases/download/release-qpdf-10.3.2/qpdf-10.3.2.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
    build-packages:
      - g++
      - zlib1g-dev
    stage-packages:
      - libjpeg-turbo8
    prime:
      - -etc/fonts
      - -var
      - -usr/include
      - -share/man
      - -share/doc
      - -share/lintian
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -usr/lib/libqpdf.a
      - -usr/lib/libqpdf.la
      - -usr/lib/pkgconfig

  ghostscript:
    source: https://github.com/ArtifexSoftware/ghostpdl-downloads/releases/download/gs9540/ghostscript-9.54.0.tar.gz
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --without-x
      - --disable-gtk
      - --with-drivers=cups,pwgraster
      - --enable-freetype
      - --without-tesseract
      - --datarootdir=/snap/hplip-printer-app/current/usr/share/
    stage-packages:
      - libpaper1
      - libfontconfig1
      - libfreetype6
      - libpng16-16
    prime:
      - -etc/fonts
      - -var
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - -snap
    organize:
      snap/hplip-printer-app/current/usr/share: usr/share

  cups:
    source: https://github.com/OpenPrinting/cups
    source-type: git
    plugin: autotools
    override-build: |
      set -eux
      ./configure --sysconfdir=/var/snap/hplip-printer-app/common/
      cd cups
      make
      cd ..
      cd ppdc
      make ppdc
      cd ..
      mkdir -p $SNAPCRAFT_STAGE/usr/lib
      cp cups/libcups*.a $SNAPCRAFT_STAGE/usr/lib/
      cp cups/libcups*.so* $SNAPCRAFT_STAGE/usr/lib/
      mkdir -p $SNAPCRAFT_STAGE/usr/include/cups
      cp cups/*.h $SNAPCRAFT_STAGE/usr/include/cups/
      mkdir -p $SNAPCRAFT_STAGE/usr/bin
      cp cups-config $SNAPCRAFT_STAGE/usr/bin/
      cp ppdc/ppdc $SNAPCRAFT_STAGE/usr/bin/
      #snapcraftctl build
    build-packages:
      - patch
      - gettext
      - autoconf
      - automake
      - libtool
      - autotools-dev
      - pkg-config
      - libavahi-client-dev
      - libavahi-common-dev
      - libavahi-compat-libdnssd-dev
      - libdbus-1-dev
      - libfontconfig1-dev
      - libfreetype6-dev
      - libgnutls28-dev
      - libjpeg-dev
      - libldap2-dev
      - libkrb5-dev
      - libpam0g-dev
      - libpaper-dev
      - libpng-dev
    stage-packages:
      - libavahi-common3
      - libavahi-client3
      - libicu66
      - libjson-glib-1.0-0
      - libsoup2.4-1
      - libxml2
    prime:
      - -etc/fonts
      - -var
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - usr/lib
      - usr/lib/libcups.so.2
      - usr/lib/libcupsimage.so.2

  cups-filters:
    source: https://github.com/OpenPrinting/cups-filters
    source-type: git
    plugin: autotools
    override-build: |
      set -eux
      ./autogen.sh
      ./configure --disable-avahi --disable-ldap --disable-foomatic --disable-braille --disable-mutool --without-rcdir --with-pdftops-path=/snap/cups/current/usr/bin/pdftops
      make libppd.la
      make libcupsfilters.la
      make libfontembed.la
      mkdir -p $SNAPCRAFT_STAGE/usr/lib
      cp .libs/lib* $SNAPCRAFT_STAGE/usr/lib/
      mkdir -p $SNAPCRAFT_STAGE/usr/include/ppd
      cp ppd/*.h $SNAPCRAFT_STAGE/usr/include/ppd/
      mkdir -p $SNAPCRAFT_STAGE/usr/include/cupsfilters
      cp cupsfilters/*.h $SNAPCRAFT_STAGE/usr/include/cupsfilters/
      mkdir -p $SNAPCRAFT_STAGE/usr/include/fontembed
      cp fontembed/*.h $SNAPCRAFT_STAGE/usr/include/fontembed/
      mkdir -p $SNAPCRAFT_STAGE/usr/lib/pkgconfig
      cp *.pc $SNAPCRAFT_STAGE/usr/lib/pkgconfig/
      #snapcraftctl build
    build-packages:
      - gettext
      - autoconf
      - automake
      - autotools-dev
      - pkg-config
      - g++
      - sharutils
      - poppler-utils
      - libglib2.0-dev
      - liblcms2-dev
      - libpoppler-cpp-dev
      - libpng-dev
      - libtiff5-dev
      - zlib1g-dev
      - libfontconfig1-dev
      - libdbus-1-dev
      - librsvg2-bin
    stage-packages:
      - poppler-utils
      - libpoppler-cpp0v5
      - libjbig0
      - liblcms2-2
      - libnspr4
      - libnss3
      - libopenjp2-7
      - libpoppler97
      - libtiff5
      - libwebp6
    prime:
      - -etc/fonts
      - -var
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - usr/lib
      - usr/lib/libcupsfilters.so.1
      - -usr/lib/libcupsfilters.so.1.0.0
      - usr/lib/libppd.so.1
      - -usr/lib/libppd.so.1.0.0
      - usr/lib/libfontembed.so.1
      - -usr/lib/libfontembed.so.1.0.0
      - usr/bin/pdftops
    after: [jpeglib, cups, qpdf, ghostscript]

  hplip:
    source: https://sourceforge.net/projects/hplip/files/hplip/3.21.6/hplip-3.21.6.tar.gz
    plugin: autotools
    build-environment:
      - PYTHON: python3
      - on amd64:
        - IMAGEPROC: enable
      - else:
        - IMAGEPROC: disable
      - on arm64:
        - SNAPCRAFT_ARCH_TRIPLET: aarch64-unknown-linux-gnu
    autotools-configure-parameters:
      - --build=$SNAPCRAFT_ARCH_TRIPLET
      - --prefix=/usr
      - --disable-foomatic-rip-hplip-install
      - --without-docdir
      - --without-htmldir
      - --with-hpppddir=/usr/share/ppd/hplip/HP
      - --without-drvdir
      - --without-icondir
      - --enable-hpcups-install
      - --disable-cups-drv-install
      - --disable-hpijs-install
      - --disable-foomatic-drv-install
      - --$IMAGEPROC-imageProcessor-build
      - --enable-network-build
      - --disable-class-driver
      - --disable-scan-build
      - --disable-gui-build
      - --disable-fax-build
      - --disable-qt3
      - --disable-qt4
      - --disable-qt5
      - --disable-policykit
    override-build: |
      set -eux
      perl -p -i -e 's:/etc/hp:/snap/hplip-printer-app/current/etc/hp:' Makefile*
      if echo $SNAPCRAFT_ARCH_TRIPLET | grep -qv x86_64; then
        perl -p -i -e 's: -lImageProcessor::' Makefile*
      fi
      snapcraftctl build
      ( cd ../install/snap/hplip-printer-app/current/etc/hp; \
        perl -p -i -e 's:/var/:/var/snap/hplip-printer-app/common/var/:' hplip.conf; \
        perl -p -i -e 's:/usr/share/:/snap/hplip-printer-app/current/usr/share/:' hplip.conf; \
        perl -p -i -e 's:/usr/share/ppd/hplip:/usr/share/ppd:' hplip.conf; \
        perl -p -i -e 's:/usr/share/ppd/HP:/usr/share/ppd:' hplip.conf; \
        perl -p -i -e 's:/usr/lib/cups/:/snap/hplip-printer-app/current/usr/lib/hplip-printer-app/:' hplip.conf; \
      )
      ( cd ../install/usr/share/hplip/
        perl -p -i -e 's:/var/(\S+)/hp:/var/snap/hplip-printer-app/common/var/\1/hp:' *.py */*.py */*/*.py
        perl -p -i -e 's:/etc/hp:/snap/hplip-printer-app/current/etc/hp:' *.py */*.py */*/*.py
      )
      ( cd ../install; \
        for file in usr/bin/hp-*; do \
          perl -p -i -e 's:^\s*\#\!\s*/usr/bin/env\s+python.*:#!/snap/hplip-printer-app/current/usr/bin/python3:' `readlink -f $file`; \
        done; \
      )
      ( cd ../install/usr/share/ppd/hplip/HP/; \
        find . -name '*.gz' | xargs gunzip -f; \
        pyppd -v -o hplip-hpcups-ppds .; \
        mv hplip-hpcups-ppds ../..; \
        cd ../..; \
        rm -rf hplip; \
      )
      ln -sf python3 ../install/usr/bin/python
      if echo $SNAPCRAFT_ARCH_TRIPLET | grep -q x86_64; then
        cp prnt/hpcups/libImageProcessor-x86_64.so ../install/usr/lib/libImageProcessor.so
      fi
    build-packages:
      - ubuntu-dev-tools
      - dpkg-dev
      - fakeroot
      - automake
      - gawk
      - python3-dev
      - libpython3-dev
      - fdupes
      - libavahi-client-dev
      - libavahi-core-dev
      - libdbus-1-dev
      - libjpeg-dev
      - libsnmp-dev
      - libssl-dev
      - libtool
      - libudev-dev
      - libusb-1.0-0-dev
      - perl-base
      - python3
      - xz-utils
      - pyppd
    stage-packages:
      - python3
      - python3-minimal
      - python3.8
      - python3.8-minimal
      - python3-dbus
      - python3-distro
      - python3-gi
      - python3-pexpect
      - python3-pil
      - python3-reportlab
      - libpython3.8
      - libpython3.8-stdlib
      - pyppd
      - wget
      - xz-utils
      - avahi-utils
      - libsnmp35
      - libsnmp-base
    organize:
      usr/lib/cups/filter/hpcups: usr/lib/hplip-printer-app/filter/hpcups
      usr/lib/cups/backend/hp: usr/lib/hplip-printer-app/backend/hp
      snap/hplip-printer-app/current/etc: etc
    stage:
      - etc
      - usr/bin
      - usr/lib
      - usr/share/hplip
      - usr/share/ppd
      - usr/share/snmp
      - usr/lib/hplip-printer-app
    prime:
      - etc
      - -var
      - usr/bin
      - usr/lib
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - usr/share/hplip
      - usr/share/ppd
      - usr/share/snmp
      - usr/lib/hplip-printer-app
      - -usr/lib/cups
    after: [cups]

  hplip-printer-app:
    plugin: make
    source: .
    make-parameters:
      - LDFLAGS="$LDFLAGS -ljpeg"
    build-packages:
      - libusb-1.0-0-dev
    stage-packages:
      - libusb-1.0-0
      - libjbig0
      - liblcms2-2
      - libtiff5
      - libwebp6
    stage:
      - -var
      - usr/bin/hplip-printer-app
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - usr/share/hplip-printer-app
      - -usr/lib/hplip-printer-app
    prime:
      - -var
      - usr/bin/hplip-printer-app
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - usr/share/hplip-printer-app
      - -usr/lib/hplip-printer-app
    after: [pappl-retrofit, pappl, cups-filters, hplip]

  mdns-lookup:
    # Make resolution of ".local" host names (Zero-Conf/mDNS/DNS-SD)
    # working: Take the original nsswitch.conf file from the base
    # Snap and add "mdns4_minimal [NOTFOUND=return]" to its "hosts:" line
    # Also install corresponding mdns4_minimal plug-in
    # See: https://forum.snapcraft.io/t/no-mdns-support-in-snaps-should-core-have-a-modified-nsswitch-conf/
    plugin: nil
    stage-packages:
      - libnss-mdns
    override-prime: |
      set -eux
      sed -Ee 's/^\s*hosts:(\s+)files/hosts:\1files mdns4_minimal \[NOTFOUND=return\]/' /snap/core20/current/etc/nsswitch.conf > $SNAPCRAFT_STAGE/etc/nsswitch.conf
      snapcraftctl prime
    prime:
      - -var
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/fonts
      - -usr/share/man
      - -usr/share/doc
      - -usr/share/doc-base
      - -usr/share/lintian
      - lib/$SNAPCRAFT_ARCH_TRIPLET/libnss_mdns4_minimal*
      - etc/nsswitch.conf

  scripts:
    plugin: dump
    source: .
    organize:
      snap/local/run-hplip-printer-app*: scripts/
      HP: usr/lib/hplip-printer-app/backend/HP
    prime:
      - scripts/
      - usr/lib/hplip-printer-app/backend/
    after: [hplip-printer-app]
